# Generated by Django 4.0.5 on 2022-06-26 21:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Category', models.CharField(choices=[(' ', ' '), ('Kira', 'Kira'), ('Faturalar', 'Faturalar'), ('Yemek', 'Yemek'), ('Kişisel Harcama', 'Kişisel Harcama'), ('Vergi', 'Vergi'), ('Diğer', 'Diğer')], default=' ', max_length=20)),
                ('Type', models.CharField(choices=[('Gelir', 'Gelir'), ('Gider', 'Gider')], max_length=10)),
                ('Balance', models.DecimalField(decimal_places=2, max_digits=20)),
                ('Client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('Date',),
            },
        ),
    ]
