# Generated by Django 4.0.5 on 2022-08-16 15:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_remove_transaction_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='Category',
            field=models.CharField(choices=[(' ', ' '), ('Debt Payment', 'Debt Payment'), ('Utilities', 'Utilities'), ('Food', 'Food'), ('Housing', 'Housing'), ('Transportation', 'Transportation'), ('Insurance', 'Insurance'), ('Medical', 'Medical'), ('Personal Spending', 'Personal Spending'), ('Entertainment', 'Entertainment'), ('Miscellaneous', 'Miscellaneous')], default=' ', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='Type',
            field=models.CharField(choices=[('Income', 'Income'), ('Expense', 'Expense')], max_length=10),
        ),
    ]
